# Build and publish Docker images for multiple architectures.
#
# Pushing an image to codeberg's container registry
# The package owner will be the repo owner.
#
# This config also shows usage of yaml aliases and
# was taken from https://codeberg.org/6543/docker-images/src/commit/37e29c227717c1c07d2776cddcf14725bf952875/.woodpecker/hello.yml

when:
  branch: main
  event: [push, pull_request, manual]

variables:
  - &context src
  - &file src/Dockerfile
  - &repo https://git.chimmie.k.vu/GamePlayer-8/dn42-rpki

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      ipv6: true
      context: *context
      dockerfile: *file
      platforms: linux/amd64
      dry_run: true
      repo: ${CI_FORGE_URL#https://}/${CI_REPO_OWNER,,}/${CI_REPO_NAME,,}
      tags: latest
    # when:
    #   event: pull_request
    #   path: *file

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      insecure: false
      ipv6: true
      context: *context
      dockerfile: *file
      platforms: linux/amd64
      repo: ${CI_FORGE_URL#https://}/${CI_REPO_OWNER,,}/${CI_REPO_NAME,,}
      registry: ${CI_FORGE_URL#https://}
      tags: latest
      username: ${CI_REPO_OWNER,,}
      password:
        from_secret: OCI_TOKEN
    # when:
    #   event: push
    #   path: *file

  publishCodeberg:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      insecure: false
      ipv6: true
      context: *context
      dockerfile: *file
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO_OWNER,,}/${CI_REPO_NAME}
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER,,}
      password:
        from_secret: OCI_CODEBERG_TOKEN
    # when:
    #   event: push
    #   path: *file
